name: Basic greeting

on:
  issue_comment:
    types: [created, deleted]

jobs:
  basic-greeting:
    name: Basic greeting
    runs-on: ubuntu-latest
    steps:
      - name: greeting
        run: |
          echo test
